plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    // Compose plugin version Kotlin version (2.1.10) à¦à¦° à¦¸à¦¾à¦¥à§‡ à¦®à¦¿à¦² à¦¥à¦¾à¦•à¦¤à§‡ à¦¹à¦¬à§‡
    id("org.jetbrains.kotlin.plugin.compose") version "2.1.10"
    id("com.google.gms.google-services") version "4.4.2"
}

android {
    namespace = "com.rasel.rasgram"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.rasel.rasgram"
        minSdk = 24
        targetSdk = 35
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary = true
        }

        ndk {
            // à¦¶à§à¦§à§ à¦®à¦¾à¦¤à§à¦° à¦†à¦§à§à¦¨à¦¿à¦• à¦«à§‹à¦¨à¦—à§à¦²à§‹à¦° à¦œà¦¨à§à¦¯ à¦¬à¦¿à¦²à§à¦¡ à¦•à¦°à¦¬à§‡, à¦à¦¤à§‡ APK à¦¸à¦¾à¦‡à¦œ à¦…à¦¨à§‡à¦• à¦•à¦®à§‡ à¦¯à¦¾à¦¬à§‡
            abiFilters += listOf("arm64-v8a", "armeabi-v7a")
        }

        // ðŸ”¥ PRO TIP: à¦²à¦¾à¦‡à¦¬à§à¦°à§‡à¦°à¦¿à¦—à§à¦²à§‹ à¦¥à§‡à¦•à§‡ à¦…à¦ªà§à¦°à§Ÿà§‹à¦œà¦¨à§€à§Ÿ à¦­à¦¾à¦·à¦¾ à¦¡à¦¿à¦²à¦¿à¦Ÿ à¦•à¦°à§‡ à¦¶à§à¦§à§ à¦‡à¦‚à¦°à§‡à¦œà¦¿ à¦“ à¦¬à¦¾à¦‚à¦²à¦¾ à¦°à¦¾à¦–à¦¬à§‡à¥¤ à¦à¦¤à§‡ à¦ªà§à¦°à¦¾à§Ÿ à§§-à§¨ MB à¦¸à¦¾à¦‡à¦œ à¦•à¦®à¦¬à§‡à¥¤
        resourceConfigurations += listOf("en", "bn")
    }

    signingConfigs {
        getByName("debug") {
            // debug keystore - auto-generated by Android
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            // Use debug signing for CI builds (unsigned APK for distribution needs keystore)
            signingConfig = signingConfigs.getByName("debug")
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
        debug {
            isMinifyEnabled = false
        }
    }

    bundle {
        language { enableSplit = true }
        density { enableSplit = true }
        abi { enableSplit = true }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true
    }

    kotlinOptions {
        jvmTarget = "17"
        freeCompilerArgs += listOf(
            "-opt-in=kotlin.RequiresOptIn",
            "-Xjvm-default=all"
        )
    }

    buildFeatures {
        compose = true
        buildConfig = false
    }

    packaging {
        resources {
            excludes += setOf(
                "/META-INF/{AL2.0,LGPL2.1}",
                "/META-INF/*.kotlin_module",
                "META-INF/DEPENDENCIES",
                "META-INF/LICENSE*",
                "META-INF/NOTICE*",
                "DebugProbesKt.bin",
                "kotlin-tooling-metadata.json"
            )
        }
        jniLibs {
            useLegacyPackaging = false
        }
    }

    lint {
        disable += setOf("MissingTranslation", "ExtraTranslation")
        checkReleaseBuilds = false
    }
}

dependencies {

    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.2")

    // â”€â”€â”€ Core Android â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    implementation("androidx.core:core-ktx:1.15.0")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.7")

    // â”€â”€â”€ Compose â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    implementation("androidx.activity:activity-compose:1.10.0")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7")
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.8.7")
    implementation("androidx.navigation:navigation-compose:2.8.6")

    val composeBom = platform("androidx.compose:compose-bom:2024.12.01")
    implementation(composeBom)
    androidTestImplementation(composeBom)

    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.runtime:runtime")
    
    // ðŸ”¥ FIX: material-icons-extended à¦°à¦¿à¦®à§à¦­ à¦•à¦°à¦¾ à¦¹à§Ÿà§‡à¦›à§‡à¥¤ à¦à¦Ÿà¦¿ à§©-à§ª MB à¦¸à¦¾à¦‡à¦œ à¦–à¦¾à§Ÿà¥¤ 
    // à¦¯à§‡ à¦†à¦‡à¦•à¦¨à¦—à§à¦²à§‹ à¦²à¦¾à¦—à¦¬à§‡ à¦¸à§‡à¦—à§à¦²à§‹ Google Fonts à¦¥à§‡à¦•à§‡ SVG à¦¡à¦¾à¦‰à¦¨à¦²à§‹à¦¡ à¦•à¦°à§‡ res/drawable à¦ à¦…à§à¦¯à¦¾à¦¡ à¦•à¦°à§‡ à¦¨à¦¿à¦¬à§‡à¦¨à¥¤
    implementation("androidx.compose.material:material-icons-core")

    // â”€â”€â”€ Image Loading â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    implementation("io.coil-kt.coil3:coil-compose:3.0.4")
    implementation("io.coil-kt.coil3:coil-network-okhttp:3.0.4")
    implementation("io.coil-kt.coil3:coil:3.0.4")

    // â”€â”€â”€ File Picker â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    implementation("androidx.documentfile:documentfile:1.0.1")

    // â”€â”€â”€ CameraX â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    val cameraxVersion = "1.4.0"
    implementation("androidx.camera:camera-core:$cameraxVersion")
    implementation("androidx.camera:camera-camera2:$cameraxVersion")
    implementation("androidx.camera:camera-lifecycle:$cameraxVersion")
    implementation("androidx.camera:camera-view:$cameraxVersion")

    // â”€â”€â”€ Firebase â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    implementation(platform("com.google.firebase:firebase-bom:33.6.0"))
    // ðŸ”¥ FIX: Analytics à¦°à¦¿à¦®à§à¦­ à¦•à¦°à¦¾ à¦¹à§Ÿà§‡à¦›à§‡ à¦ªà¦¾à¦°à¦«à¦°à¦®à§à¦¯à¦¾à¦¨à§à¦¸ à¦¬à§à¦¸à§à¦Ÿ à¦à¦¬à¦‚ à¦¸à¦¾à¦‡à¦œ à¦•à¦®à¦¾à¦¨à§‹à¦° à¦œà¦¨à§à¦¯
    implementation("com.google.firebase:firebase-auth-ktx")
    implementation("com.google.firebase:firebase-firestore-ktx")
    implementation("com.google.firebase:firebase-storage-ktx")
    
    // Firebase Cloud Messaging (FCM) - à¦¨à§‹à¦Ÿà¦¿à¦«à¦¿à¦•à§‡à¦¶à¦¨à§‡à¦° à¦œà¦¨à§à¦¯ à¦†à¦—à§‡à¦° à¦§à¦¾à¦ªà§‡ à¦¬à¦²à§‡à¦›à¦¿à¦²à¦¾à¦®
    implementation("com.google.firebase:firebase-messaging-ktx")
    
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.9.0")

    // â”€â”€â”€ ML Kit â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    // ðŸ”¥ FIX: à¦šà§à¦¯à¦¾à¦Ÿ à¦…à§à¦¯à¦¾à¦ªà§‡ Barcode à¦¬à¦¾ Text Recognition à¦¦à¦°à¦•à¦¾à¦° à¦¨à§‡à¦‡à¥¤ 
    // à¦à¦—à§à¦²à§‹ à¦ªà§à¦°à¦¾à§Ÿ à§§à§¦-à§§à§« MB à¦¸à¦¾à¦‡à¦œ à¦¨à¦¿à§Ÿà§‡ à¦¨à¦¿à¦šà§à¦›à¦¿à¦²à¥¤ à¦¤à¦¾à¦‡ à¦¬à¦¾à¦¦ à¦¦à§‡à¦“à§Ÿà¦¾ à¦¹à¦²à§‹à¥¤
    // implementation("com.google.mlkit:barcode-scanning:17.3.0")
    // implementation("com.google.mlkit:text-recognition:16.0.1")

    // â”€â”€â”€ WebRTC (~15MB) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    // à¦­à¦¿à¦¡à¦¿à¦“ à¦¬à¦¾ à¦…à¦¡à¦¿à¦“ à¦•à¦²à§‡à¦° à¦œà¦¨à§à¦¯ à¦à¦Ÿà¦¿ à¦®à¦¾à¦¸à§à¦Ÿ à¦²à¦¾à¦—à¦¬à§‡, à¦¤à¦¾à¦‡ à¦à¦Ÿà¦¿ à¦°à¦¾à¦–à¦¾ à¦¹à¦²à§‹à¥¤ 
    implementation("io.getstream:stream-webrtc-android:1.1.1")
    
    // Push Notification à¦à¦° à¦œà¦¨à§à¦¯ OkHttp
    implementation("com.squareup.okhttp3:okhttp:4.11.0")
    // FCM v1 API à¦à¦° Access Token à¦œà§‡à¦¨à¦¾à¦°à§‡à¦Ÿ à¦•à¦°à¦¾à¦° à¦œà¦¨à§à¦¯
    implementation("com.google.auth:google-auth-library-oauth2-http:1.19.0")

    // â”€â”€â”€ Testing â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.2.1")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.6.1")
    androidTestImplementation("androidx.compose.ui:ui-test-junit4")
    debugImplementation("androidx.compose.ui:ui-tooling")
    debugImplementation("androidx.compose.ui:ui-test-manifest")
}
